### ISSUE TITLE
imageservice/cp should respect Image API format

### ISSUE THREAD

**Issue by hbalenda** [digirati-co-uk/iiif-canvas-panel#193]
Attempting to render an `<image-service>` using an image API that only serves `png` tiles results in requests for `jpg` tiles. The same happens with a `<canvas-panel>` rendering a canvas containing an annotation that uses an image API that only serves `png` (have not tested other file formats).

I've tested with level 0 implementations using the [2.0 Image API](https://gist.github.com/hbalenda/7676715e97afc744d2637d04ffff1c81) and [3.0](https://gist.githubusercontent.com/hbalenda/f35309470aaaeceeb709b200182d5fcc/raw/285c47b7a73f557f9a07d16c87db444711c37b6f/example-png-image-service-3.json).  I know the `preferredFormats` option is still under development, but thought this might be a separate issue.

**Comment by stephenwf** [comment]
At the moment the [IIIF Image API](https://iiif.io/api/image/3.0/compliance/#35-format) requires that level0 supports jpg tiles to be valid. But I do think we should have support for the `preferredFormats` option for images that are better viewed in this way. 

cc/ @tomcrane
