### ISSUE TITLE
Canvas Panel method `makeChoice` is not defined on load

### ISSUE THREAD

**Issue by hbalenda** [digirati-co-uk/iiif-canvas-panel#200]
The `makeChoice` method appears to be defined asynchronously on canvas panels, and it's not clear how await it.

The issue seems to be worse in Firefox, but have also seen it on Chrome and Safari.

See codepen: https://codepen.io/hbalenda/pen/ZEoZPjN

**Comment by stephenwf** [comment]
There is a choice event that you can listen to, that will be fired when there are available choices. 
```js
cp.addEventListener('choice', (ev) => {
  isMakeChoiceLoaded();
});
```

The event passed in has a `ev.detail` property with the following shape:
```typescript
interface SingleChoice {
    type: 'single-choice';
    label?: InternationalString;
    items: Array<{
        id: string;
        label?: InternationalString;
        selected?: true;
    }>;
}
```
