### ISSUE TITLE
Annotation Styling

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-canvas-panel#93]
"Draw a box" - but not the user drawing a box (that come later!)

This issue is supporting the features described here:
https://deploy-preview-50--iiif-canvas-panel.netlify.app/docs/examples/drawing-boxes/

CP showing a region is covered by #69 

This is making a visible change. Via attributes:

```html
<canvas-panel
   iiif-content=https://data.ng-london.org.uk/iiif/0CWR-0001-0000-0000/canvas/-1
   partof=https://data.ng-london.org.uk/iiif/0CWR-0001-0000-0000/manifest
   region="2000,2000,1000,1000"
   highlight="2400,2400,400,400"
   highlight-css-class="red-box"
/>
```

In code, this reveals dependencies on two other features, Target and DisplayAnnotation as wrapper.
These features are [still under discussion](https://github.com/digirati-co-uk/iiif-canvas-panel/discussions/33). (https://github.com/digirati-co-uk/iiif-canvas-panel/discussions/33)

```html
<canvas-panel id="cp"></canvas-panel>
<script>
   const vault = new Vault();
   const cp = document.getElementById("cp");
   await vault.loadManifest("..manifest_id..");
   cp.setCanvas("..canvas_id..");

   // set the viewport to a region:
   // With no additional arguments, there is no animation
   cp.goToTarget(new Target("xywh=2000,2000,1000,1000"));

   // draw a box in this region (the verbose way, for comparison, but could be short form):
   const redBoxTarget = new Target();
   redBoxTarget.spatial.x = 2400;
   redBoxTarget.spatial.y = 2400;
   redBoxTarget.spatial.w = 400;
   redBoxTarget.spatial.h = 400;
  
   // create an annotation with motivation "highlighting"
   const anno = new HighlightingAnnotation();
   anno.target = redBoxTarget;
  
  // here I could ask for anno.toW3CAnno() and get a pure W3C JSON
  

   // create anno in vault
   vault.load("my-anno", anno);


   const displayAnno = new DisplayAnnotation(vault.FromRef("my-anno"));
   displayAnno.cssClass = "red-box";
       
   cp.DisplayAnnotations.add(displayAnno);
   
   // could go-native here with 
   // cp.worldObject.appendChild( ... );

</script> 
```

**Comment by tomcrane** [comment]
In summary - make https://deploy-preview-50--iiif-canvas-panel.netlify.app/docs/examples/drawing-boxes/ work!

**Comment by tomcrane** [comment]
What CSS can be applied to a DisplayAnnotation?

- border-color
- border-style
- border-width
- background-color (including opacity)

To be sorted:
- background-attachment
- background-clip
- background-image
- background-origin
- background-position
- background-repeat
- background-size

**Comment by stephenwf** [comment]
Summary of supported canvas styles:

**Border / Outline**
Same rules for both, just `border` -> `outline`.

```javascript
{ border: '1px solid red' }; // ✅ short hand properties
{ border: '1px solid rgb(255, 0, 0)' }; // ✅ RGB colour values (and other functions)
{ border: '1px solid rgba(255, 0, 0, .5)' }; // ✅ Colours with alpha
{ borderColor: 'red', borderWidth: '1px', borderStyle: 'solid' }; // ✅  borderXYZ properties

{ border: '1px 10px 0 0 solid red' };  // 🟡 Extra widths will be ignored, width will be 1px
{ border: '1em solid red' };  // 🟡 em/relative units will be read as pixels (1em -> 1px)

{ border: '1px dashed red' }; // ❌ Only "solid" supported currently
{ borderLeftWidth: '1px' }; // ❌ No per-side properties
```

**Background**
Currently only `backgroundColor` is supported, and shorthand is not supported.
```javascript
{ background: 'red' }; // ✅ shorthand background color
{ backgroundColor: 'red' }; // ✅ background colour property
{ backgroundColor: 'rgba(255, 0, 0, 0.5)' }; // ✅ background colour property with alpha

{ backgroundImage: 'url(...)' }; // ❌ No other types of background
{ backgroundRepeat: 'repeat' }; // ❌ No other types of background
{ background: 'linear-gradient(...)' }; // ❌ No shorthand background that is not a colour
```

**Box shadow**
Most box shadows are supported. From the mozilla docs:
```javascript
{ boxShadow: '10px 5px 5px red' }; // ✅ normal shadows
{ boxShadow: '60px -16px teal' }; // ✅ negative values and short hand props
{ boxShadow: '12px 12px 2px 1px rgba(0, 0, 255, .2)' }; // ✅ alpha colours
{ boxShadow: '3px 3px red, 4px 0 4px olive' }; // ✅ Multiple shadows

{ boxShadow: '5em 1em gold' }; // 🟡 em/relative units will be displays as pixels.

{ boxShadow: 'inset 5px 1px gold' }; // ❌ Inset shadows are not supported
```

**Hover / active states**
Similar to CSS-in-JS libraries, you can style hover/active states for annotations.
```js
{
  background: 'green',

  // Hover styles
  ':hover': {
    background: 'red'
  },

  // Active/pressed styles
  ':active': {
    background: 'blue'
  },
}
```
_Note: active styles will be removed when your pointer/mouse leaves the box. This is slightly different to browser behaviour._

**HTML rendering**
If you want to style something using CSS/HTML without these limitations then you can. Adding a classname to an annotation or annotation-list will de-optimise it. The style properties above will continue to work, but without the states limitations (and all other CSS properties).

_In Atlas you can add either a `className="my-css-class"` or `html="true"` to force using the HTML renderer._

In the underlying viewer, although you may have an HTML `<div />` to represent an annotation, that doesn't mean that pointer events will be handled by that element. All events are handled internally by the viewer by default. This allows panning, zooming and other event handlers to continue to work with a mix of canvas and HTML elements. One side effect of this is that your CSS class may not work with states. For example:
```html
<style>
  .my-annotation {
    background: red;
  }
  .my-annotation:hover { /* ❌ :hover may not react to pointer events */
    background: blue;
  }
</style>
```
May not work as expected. When you hover in atlas, we will take your class name and append `--hover` or `--active` to the class name. The following style is recommended:
```html
<style>
  .my-annotation {
    background: red;
  }
  .my-annotation--hover, /* ✅ covers both types of hover */
  .my-annotation:hover { 
    background: blue;
  }
  .my-annotation--active,  /* ✅ covers both types of active */
  .my-annotation:hover:active { 
    background: orange;
  }
</style>
```

**Comment by stephenwf** [comment]
## CSS styling

There are 3 ways of styling with CSS.

**1. Reference an external stylesheet.**

```html
<canvas-panel stylesheet="/annotations.css" annotation-css-class="example-annotation" />
```

**2. Reference a style tag**
```html
<style id="my-style">
  .example-annotation {
    background: red;
  }
</style>

...

<canvas-panel style-id="my-style" annotation-css-class="example-annotation" />
```

**3. Using CSS `::part` selector**
```html
<style>
  /* ✅ tip: you can optionally add a class name if you have multiple */
  canvas-panel.custom-class::part(example-annotation) {
    background: red;  
  }
</style>

<canvas-panel class="custom-class" annotation-css-class="example-annotation" />
```
CSS using the `::part` selector can be external or inline.
